### ISSUE TITLE
dockle latest version

### ISSUE THREAD

**Issue by NikLeberg** [erzz/dockle-action#15]
The parsing for the latest dockle version no longer works. The dockle repository seems to have deleted the v0.4.5 release or its tag. But it still works if I set `dockle-version: "0.4.5"`.

**Comment by erzz** [comment]
Hi @NikLeberg 

Seems like it was a temporary issue - possibly with github api (as I have seen several actions from other people resulting in failures overnight!) 

I just stepped through the curls and commands plus reran tests and all seems OK now?

**Comment by erzz** [comment]
not getting much response to the issue I raised, but it does seem like they have (re)created their releases now and so hopefully we are resolved here

Feel free to reopen if you think not or that it can be handled in a better way (perhaps switch to tags rather than releases)
