### ISSUE TITLE
Unable to resolve action `erzz/dockle-action@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by donhector** [erzz/dockle-action#8]
![image](https://user-images.githubusercontent.com/2475379/156963449-32ba324f-179c-4857-b43a-80add01e971c.png)

The examples in the README file all point to version `v1`, however that tag does not seem to exist in this repo

Using `master` or `v1.1.1` works fine.

README file should be updated to point to an existing tag

**Comment by erzz** [comment]
Thanks - I need to update the semantic-release process to have floating tags too. Thanks for picking it up, it sucks when docs let you down!
